version: "3"

services:
  postgres1:
    image: postgres:16
    container_name: postgres1
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata1:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  postgres2:
    image: postgres:16
    container_name: postgres2
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata2:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  postgres3:
    image: postgres:16
    container_name: postgres3
    environment:
      POSTGRES_USER: user3
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener
    ports:
      - "5435:5432"
    volumes:
      - ./pgdata3:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata1:
  pgdata2:
  pgdata3:
